cloud:
  aws:
    credentials:
      access-key: AKIA6N6B5OYKWQYPI37N
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  bucket:
    name: people-hub-image-storage01


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 9090